//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrozenYogurtDBFirstWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class kampanyaliurun
    {
        public int BaslikId { get; set; }
        public string BaslikAdi { get; set; }
        public string BaslikAciklamasi { get; set; }
        public string BaslikIcerikAdi { get; set; }
        public string BaslikFiyat { get; set; }
    }
}
