//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrozenYogurtDBFirstWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FrozenYogurtEntities : DbContext
    {
        public FrozenYogurtEntities()
            : base("name=FrozenYogurtEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<iletisim> iletisim { get; set; }
        public virtual DbSet<kategori> kategori { get; set; }
        public virtual DbSet<urun> urun { get; set; }
        public virtual DbSet<kampanyaliurun> kampanyaliurun { get; set; }
        public virtual DbSet<adminuser> adminuser { get; set; }
    }
}
